spring:
  application:
    name: capyjara-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 192.168.1.1:8848
        username: nacos
        group: DEFAULT_GROUP
      config:
        namespace: public
        server-addr: 192.168.1.1:8848
        username: nacos
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:swagger-gateway.yaml
      - nacos:redis.yaml
      - nacos:redisson.yaml
      - nacos:${spring.application.name}.yaml
  security:
    oauth2:
      client:
        registration:
          capyId:
            provider: capyjara
            client-id: capyId
            client-secret: capySecret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            # Spring Security oauth2Login自动配置的endpoint
            redirect-uri: http://192.168.216.109:8080/login/oauth2/code/{registrationId}
            scope: profile
            client-name: Capyjara
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
        provider:
          capyjara:
            authorization-uri: http://192.168.216.109:8080/auth/oauth2/authorize
            token-uri: http://192.168.216.109:8080/auth/oauth2/token
            jwk-set-uri: http://192.168.216.109:8080/auth/oauth2/jwks
#            user-info-uri: http://192.168.216.109:8080/auth/userinfo
            user-info-uri: http://192.168.216.109:8080/auth/me
            user-name-attribute: sub
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
  session:
    timeout: 60
    redis:
      repository-type: indexed
      namespace: "spring:session:gateway"

server:
  reactive:
    session:
      cookie:
        name: CAPY-GW-SESSION
        http-only: true