spring:
  application:
    name: capyjara-admin-server
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 192.168.1.1:8848
        group: DEFAULT_GROUP
      config:
        namespace: public
        server-addr: 192.168.1.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      # 优先级: 从低到高
      - nacos:swagger.yaml
      - nacos:flyway.yaml
      - nacos:mysql.yaml
      - nacos:redis.yaml
      - nacos:xxl-job.yaml
      - nacos:oauth2-jwks.yaml
      - nacos:${spring.application.name}.yaml
springdoc:
  info:
    version: @project.version@